=== VladislavKabral/EPAM_Second_Task/XML_Task/src/main/resources/gemsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/gems"
        xmlns:tns="http://www.example.com/gems"
        elementFormDefault="qualified">
        <element name="gems">
                <complexType>
                        <sequence>
                                <element name="diamond" type="tns:Diamond" minOccurs="0" maxOccurs="100"/>
                                <element name="pearl" type="tns:Pearl" minOccurs="0" maxOccurs="100"/>
                        </sequence>
                </complexType>
        </element>
        <complexType name="Diamond">
                <sequence>
                        <element name="color" type="string"/>
                        <element name="countOfEdges">
                                <simpleType>
                                        <restriction base="positiveInteger">
                                                <pattern value="([3-9]){1}|10|11|12"/>
                                        </restriction>
                                </simpleType>
                        </element>
                </sequence>
                <attribute name="id" type="tns:Id" use="required"/>
                <attribute name="origin" type="tns:Origin" use="optional" default="underground"/>
        </complexType>
        <complexType name="Pearl">
                <sequence>
                        <element name="color" type="string"/>
                        <element name="radius">
                                <simpleType>
                                        <restriction base="positiveInteger">
                                                <pattern value="[1-9]{1}"/>
                                        </restriction>
                                </simpleType>
                        </element>
                </sequence>
                <attribute name="id" type="tns:Id" use="required"/>
                <attribute name="origin" type="tns:Origin" use="optional" default="underground"/>
        </complexType>
        <simpleType name="Id">
                <restriction base="ID">
                        <pattern value="([a-zA-Z])[a-zA-Z0-9]{7,19}"/>
                </restriction>
        </simpleType>
        <simpleType name="Origin">
                <restriction base="string">
                        <enumeration value="underground">
                        </enumeration>
                        <enumeration value="underwater">
                        </enumeration>
                        <enumeration value="mountain">
                        </enumeration>
                </restriction>
        </simpleType>
</schema>

=== VladislavKabral/EPAM_Second_Task/XML_Task/src/main/resources/gems.xml
<?xml version="1.0" encoding="UTF-8"?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.example.com/gems"
      xsi:schemaLocation="http://www.example.com/gems gemsSchema.xsd">
      <diamond id="GEM12345" origin="underground">
          <color>red</color>
          <countOfEdges>9</countOfEdges>
      </diamond>
      <diamond id="GEM12346" origin="underwater">
          <color>green</color>
          <countOfEdges>10</countOfEdges>
      </diamond>
      <diamond id="GEM12347" origin="mountain">
          <color>blue</color>
          <countOfEdges>7</countOfEdges>
      </diamond>
      <pearl id="GEM98765" origin="underwater">
          <color>white</color>
          <radius>7</radius>
      </pearl>
      <pearl id="GEM98764" origin="underwater">
          <color>pink</color>
          <radius>5</radius>
      </pearl>
      <pearl id="GEM98763" origin="underwater">
          <color>white</color>
          <radius>9</radius>
      </pearl>
</gems>
